/*
 * Generated by XDoclet - Do not edit!
 */
package com.bo.process.ejb.interfaces;

/**
 * Home interface for CommonDispatcher.
 * 
 * @wtp generated
 */
public interface CommonDispatcherHome extends javax.ejb.EJBHome {

	public CommonDispatcher create() throws javax.ejb.CreateException, java.rmi.RemoteException;

}
