/*
 * Generated by XDoclet - Do not edit!
 */
package com.bo.process.ejb.interfaces;

import javax.ejb.EJBException;

import com.bo.process.ProcessResult;
import com.bo.process.transfer.VTObject;

/**
 * Remote interface for CommonDispatcher.
 * 
 * @wtp generated
 */
public interface CommonDispatcher extends javax.ejb.EJBObject {
	
	/**
	 * An example business method
	 * 
	 * @throws EJBException
	 *             Thrown if method fails due to system-level error.
	 */
	public ProcessResult processRequest(VTObject inputDTO) throws java.rmi.RemoteException;
}
